import type { AgentConfig, AuditEvent, CallRun, DebtorCase } from "./types";

export const demoCases: DebtorCase[] = [
  {
    id: "case_1001",
    caseReference: "INK-1001",
    debtorName: "Max Mustermann",
    phone: "+491701234567",
    email: "max@example.com",
    amountCents: 18420,
    creditorName: "Demo Energie GmbH",
    dueDate: "2026-03-15",
    reason: "Offene Rechnung",
    status: "new",
    nextAction: "Erstanruf vorbereiten",
    riskFlags: [],
  },
  {
    id: "case_1002",
    caseReference: "INK-1002",
    debtorName: "Sara Beispiel",
    phone: "+4915112345678",
    email: "sara@example.com",
    amountCents: 52990,
    creditorName: "Muster Shop AG",
    dueDate: "2026-02-28",
    reason: "Unbezahlter Kauf auf Rechnung",
    status: "payment_link_sent",
    lastContactAt: "2026-04-28T10:24:00.000Z",
    nextAction: "Zahlungseingang in 3 Tagen prüfen",
    riskFlags: ["Ratenwunsch"],
  },
  {
    id: "case_1003",
    caseReference: "INK-1003",
    debtorName: "Jonas Demo",
    phone: "+49301234567",
    email: "jonas@example.com",
    amountCents: 7640,
    creditorName: "Beispiel Services UG",
    dueDate: "2026-01-11",
    reason: "Servicevertrag",
    status: "disputed",
    lastContactAt: "2026-04-27T15:10:00.000Z",
    nextAction: "Menschliche Prüfung: Forderung bestritten",
    riskFlags: ["Widerspruch"],
  },
];

export const demoAgentConfigs: AgentConfig[] = [
  {
    id: "agent_default_v1",
    name: "Fair Collection DE",
    version: 1,
    isActive: true,
    voiceProvider: "vapi",
    telephony: "Twilio BYO Number via Vapi",
    transcriber: "Deepgram Nova-3 de",
    model: "gpt-4.1-mini",
    ttsVoice: "Azure de-DE-FlorianMultilingualNeural",
    temperature: 0.2,
    updatedAt: "2026-04-29T09:00:00.000Z",
    guidelines: [
      "Du bist ein KI-Telefonassistent eines Inkassobüros.",
      "Lege zu Beginn offen, dass du ein KI-Assistent bist.",
      "Sprich ruhig, fair, lösungsorientiert und ohne Druck.",
      "Prüfe die Identität sparsam, bevor du Falldetails nennst.",
      "Gib keine Rechtsberatung und mache keine Drohungen.",
      "Wenn die Forderung bestritten wird, beende das Inkasso-Gespräch freundlich und markiere den Fall zur menschlichen Prüfung.",
      "Sende Zahlungslinks nur nach Zustimmung.",
    ].join("\n"),
  },
  {
    id: "agent_soft_v1",
    name: "Soft Reminder DE",
    version: 1,
    isActive: false,
    voiceProvider: "vapi",
    telephony: "Twilio BYO Number via Vapi",
    transcriber: "Deepgram Nova-3 multi",
    model: "gpt-4.1-mini",
    ttsVoice: "Azure de-DE-FlorianMultilingualNeural",
    temperature: 0.1,
    updatedAt: "2026-04-29T09:10:00.000Z",
    guidelines: "Sehr kurzer Erinnerungsanruf. Keine Verhandlung. Bei Rückfragen an Mensch übergeben.",
  },
  {
    id: "agent_elevenlabs_test_v1",
    name: "Voice Test ElevenLabs",
    version: 1,
    isActive: false,
    voiceProvider: "vapi",
    telephony: "Twilio BYO Number via Vapi",
    transcriber: "Deepgram Nova-3 de",
    model: "claude-3-5-haiku",
    ttsVoice: "ElevenLabs German business voice",
    temperature: 0.1,
    updatedAt: "2026-04-29T09:20:00.000Z",
    guidelines:
      "Testvariante fuer Stimme und Latenz. Gleiche Compliance-Regeln wie Default. Antworten kurz halten.",
  },
];

export const demoCallRuns: CallRun[] = [
  {
    id: "call_2001",
    caseId: "case_1002",
    agentConfigId: "agent_default_v1",
    status: "completed",
    startedAt: "2026-04-28T10:24:00.000Z",
    durationSeconds: 384,
    outcome: "payment_link_sent",
    transcriptSummary:
      "Schuldnerin konnte die Forderung zuordnen, wünscht Zahlung per Link und bittet um 3 Tage Frist.",
    recordingUrl: "https://example.com/recordings/call_2001",
  },
];

export const demoAuditEvents: AuditEvent[] = [
  {
    id: "audit_3001",
    caseId: "case_1002",
    label: "Payment-Link gesendet",
    detail: "Personalisierte E-Mail mit Zahlungslink wurde vorbereitet.",
    createdAt: "2026-04-28T10:31:00.000Z",
  },
  {
    id: "audit_3002",
    caseId: "case_1003",
    label: "Widerspruch erkannt",
    detail: "Agent hat Gespräch gestoppt und menschliche Prüfung angelegt.",
    createdAt: "2026-04-27T15:13:00.000Z",
  },
];
